/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Panel_eventos.java
 *
 * Created on 13-may-2013, 12:57:39
 */
package agenda;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.ResultSet;
import javax.swing.JLabel;

/**
 *
 * @author juanki
 */
public class Panel_eventos extends javax.swing.JPanel {
private java.text.SimpleDateFormat sdf=new java.text.SimpleDateFormat("dd/MM/yyyy");  
private Operaciones operaciones=new Operaciones();   
    /** Creates new form Panel_eventos */
    public Panel_eventos() {
        initComponents();
        initComponets2();
    }
    public void initComponets2()
    {
        System.out.println(calendario.getDate());
        System.out.println(calendario.getDayChooser());
        
        MiEvento evento=new MiEvento();
        Object o=new Object();
        //calendario.action(evento, o);
        Boton_buscar.addActionListener(evento);
                
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        calendario = new com.toedter.calendar.JCalendar();
        jLabel1 = new javax.swing.JLabel();
        Boton_buscar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        panel_eventos = new javax.swing.JPanel();

        calendario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                calendarioMouseClicked(evt);
            }
        });

        Boton_buscar.setText("Buscar");
        Boton_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_buscarActionPerformed(evt);
            }
        });

        jLabel3.setText("Seleciona una fecha");

        javax.swing.GroupLayout panel_eventosLayout = new javax.swing.GroupLayout(panel_eventos);
        panel_eventos.setLayout(panel_eventosLayout);
        panel_eventosLayout.setHorizontalGroup(
            panel_eventosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 232, Short.MAX_VALUE)
        );
        panel_eventosLayout.setVerticalGroup(
            panel_eventosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 296, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(panel_eventos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(calendario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(71, 71, 71)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(62, 62, 62)
                                .addComponent(Boton_buscar))))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(74, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Boton_buscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addGap(3, 3, 3)
                        .addComponent(jLabel2)
                        .addGap(56, 56, 56)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(calendario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void Boton_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_buscarActionPerformed
         
         jLabel1.setText("Eventos");           
         String fecha=sdf.format(calendario.getDate());
         jLabel2.setText(fecha);
         operaciones.get_eventos(fecha);
         listar_resp(operaciones.get_eventos(fecha));
    }//GEN-LAST:event_Boton_buscarActionPerformed
   
    private void calendarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_calendarioMouseClicked
         String fecha=sdf.format(calendario.getDate());
         jLabel2.setText(fecha);
    }//GEN-LAST:event_calendarioMouseClicked

    public void listar_resp(ResultSet matriz)
    {
        
        panel_eventos.removeAll();
        
        try{
          int i=0;  
          while(matriz.next())
          {
           JPanelTransparente paneli =new JPanelTransparente();
           paneli.setBounds(5, (55*i)+10, 160, 50);
           paneli.setToolTipText(matriz.getString(3));
           
           JLabel texto=new JLabel();
           texto.setText(matriz.getString(2));
           texto.setBounds(5, 0, 400, 40);
           
           paneli.add(texto);
           panel_eventos.add(paneli);
           i++;
          }  
          
            
          }catch(Exception e){
             System.out.println("Problema al imprimir la base de datos en listar_resp");
        }
        //panel.repaint();
        panel_eventos.setVisible(true);
        panel_eventos.repaint();
     
        System.out.println("llego hasta recyperar consulta");
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Boton_buscar;
    private com.toedter.calendar.JCalendar calendario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panel_eventos;
    // End of variables declaration//GEN-END:variables
class MiEvento implements ActionListener{
	
  public void actionPerformed( ActionEvent e ){
			
  
    if( e.getSource().equals( Boton_buscar ) )
    {
     // (Date)calendario.getDayChooser();
    }
    
  }
			
}
}
