
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import javax.swing.JLabel;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Ventana_Evento.java
 *
 * Created on 13-jun-2013, 15:03:58
 */
/**
 *
 * @author juanki
 */
public class Ventana_Evento extends javax.swing.JDialog {

    /** Creates new form Ventana_Evento */
    SimpleDateFormat formatoDeFecha = new SimpleDateFormat("dd/MM/yyyy");
    JLabel texto_nombre=new JLabel();
    JLabel texto_fecha=new JLabel();
    JLabel texto_hora_ini=new JLabel();
    JLabel texto_hora_fin=new JLabel();
    
    
    public Ventana_Evento(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        init_componentes();
    }
    public void init_componentes()
    {
        
        setLayout(null);
        hora_fin.addItem("--");
    for (int h = 0; h < 24; h++) {
      hora_fin.addItem(h);
      hora_ini.addItem(h);
    }
   
    minuto_fin.addItem("--");
    for (int m = 0; m < 60; m++) {
      minuto_fin.addItem(m);
      minuto_ini.addItem(m);
    }
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    public void set_evento(Evento evento)
    {
        inicializar_textos_labels();
        
        texto_nombre.setText(evento.getNombre());
        texto_fecha.setText(evento.getFecha());
        texto_hora_ini.setText(evento.getHora_Ini()+" : "+evento.getMinuto_ini());
        texto_hora_fin.setText(evento.getHora_Fin()+" : "+evento.getMinuto_Fin());
        
        nombre.setText(evento.getNombre());
        try{
        fecha.setDate(formatoDeFecha.parse(evento.getFecha()));
        } catch (ParseException ex) {
         ex.printStackTrace();
        }
        hora_ini.setSelectedItem(Integer.parseInt(evento.getHora_Ini()));
        minuto_ini.setSelectedItem(Integer.parseInt(evento.getMinuto_ini()));
        hora_fin.setSelectedItem(evento.getHora_Fin());
        minuto_fin.setSelectedItem(evento.getMinuto_Fin());
        
        
        nombre.setVisible(false);
        fecha.setVisible(false);
        hora_fin.setVisible(false);
        hora_ini.setVisible(false);
        minuto_ini.setVisible(false);
        minuto_fin.setVisible(false);
        l_dos_puntos.setVisible(false);
        l_dos_puntos1.setVisible(false);
       /* l_nombre.setVisible(false);
        l_hora.setVisible(false);
        l_A.setVisible(false);
        l_DE.setVisible(false);
        l_contactos.setVisible(false);
        l_fecha.setVisible(false);
        */
    }
    public void inicializar_textos_labels()
    {
        texto_nombre.setBounds(100, 25, 100,30 );
        texto_fecha.setBounds(100, 65, 100, 30);
        texto_hora_ini.setBounds(130, 92, 100, 30);
        texto_hora_fin.setBounds(130, 124, 100, 30);
        
        
        add(texto_hora_ini);
        add(texto_hora_fin);
        add(texto_fecha);
        add(texto_nombre);
        
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        l_nombre = new javax.swing.JLabel();
        l_fecha = new javax.swing.JLabel();
        l_hora = new javax.swing.JLabel();
        l_contactos = new javax.swing.JLabel();
        nombre = new javax.swing.JTextField();
        fecha = new com.toedter.calendar.JDateChooser();
        l_dos_puntos = new javax.swing.JLabel();
        hora_ini = new javax.swing.JComboBox();
        minuto_ini = new javax.swing.JComboBox();
        hora_fin = new javax.swing.JComboBox();
        minuto_fin = new javax.swing.JComboBox();
        l_dos_puntos1 = new javax.swing.JLabel();
        l_DE = new javax.swing.JLabel();
        l_A = new javax.swing.JLabel();
        editar = new javax.swing.JButton();
        cancelar = new javax.swing.JButton();
        aceptar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        l_nombre.setText("Nombre :");

        l_fecha.setText("Fecha :");

        l_hora.setText("Hora :");

        l_contactos.setText("Contactos :");

        nombre.setText("jTextField1");

        l_dos_puntos.setText(":");

        l_dos_puntos1.setText(":");

        l_DE.setText("De");

        l_A.setText("A");

        editar.setText("Editar");
        editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarActionPerformed(evt);
            }
        });

        cancelar.setText("Cancelar");
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });

        aceptar.setText("Aceptar");
        aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(l_A)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(l_hora)
                                    .addGap(28, 28, 28)
                                    .addComponent(l_DE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(editar)
                                    .addComponent(l_contactos))))
                        .addGap(8, 8, 8))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(l_fecha)
                            .addComponent(l_nombre))
                        .addGap(37, 37, 37)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nombre, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(fecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addComponent(hora_fin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(l_dos_puntos1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(minuto_fin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(hora_ini, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(l_dos_puntos, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(minuto_ini, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(aceptar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cancelar)
                .addGap(93, 93, 93))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l_nombre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l_fecha))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l_dos_puntos)
                    .addComponent(minuto_ini, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hora_ini, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l_hora)
                    .addComponent(l_DE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(minuto_fin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hora_fin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(l_dos_puntos1)
                    .addComponent(l_A))
                .addGap(3, 3, 3)
                .addComponent(l_contactos)
                .addGap(108, 108, 108)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(aceptar)
                        .addComponent(editar))
                    .addComponent(cancelar, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarActionPerformed
        texto_fecha.setVisible(false);
        texto_hora_fin.setVisible(false);
        texto_hora_ini.setVisible(false);
        texto_nombre.setVisible(false);
        nombre.setVisible(true);
        fecha.setVisible(true);
        hora_ini.setVisible(true);
        hora_fin.setVisible(true);
        minuto_fin.setVisible(true);
        minuto_ini.setVisible(true);
        l_dos_puntos.setVisible(true);
        l_dos_puntos1.setVisible(true);
        l_A.setVisible(true);
        l_DE.setVisible(true);
        l_contactos.setVisible(true);
        l_fecha.setVisible(true);
    }//GEN-LAST:event_editarActionPerformed

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
         dispose();  
    }//GEN-LAST:event_cancelarActionPerformed

    private void aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarActionPerformed
        dispose();
    }//GEN-LAST:event_aceptarActionPerformed
  
    /**
     * @param args the command line arguments
     */
    /*public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                Ventana_Evento dialog = new Ventana_Evento(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }*/
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceptar;
    private javax.swing.JButton cancelar;
    private javax.swing.JButton editar;
    private com.toedter.calendar.JDateChooser fecha;
    private javax.swing.JComboBox hora_fin;
    private javax.swing.JComboBox hora_ini;
    private javax.swing.JLabel l_A;
    private javax.swing.JLabel l_DE;
    private javax.swing.JLabel l_contactos;
    private javax.swing.JLabel l_dos_puntos;
    private javax.swing.JLabel l_dos_puntos1;
    private javax.swing.JLabel l_fecha;
    private javax.swing.JLabel l_hora;
    private javax.swing.JLabel l_nombre;
    private javax.swing.JComboBox minuto_fin;
    private javax.swing.JComboBox minuto_ini;
    private javax.swing.JTextField nombre;
    // End of variables declaration//GEN-END:variables
}
